#!/usr/bin/env groovy
import hudson.security.*
import jenkins.model.*

def instance = Jenkins.getInstance()

instance.getExtensionList(jenkins.security.s2m.MasterKillSwitchWarning.class)[0].disable(true)
instance.getExtensionList(jenkins.diagnostics.RootUrlNotSetMonitor.class)[0].disable(true)
instance.getExtensionList(hudson.PluginManager$PluginCycleDependenciesMonitor.class)[0].disable(true)
instance.getExtensionList(hudson.PluginManager$PluginUpdateMonitor.class)[0].disable(true)
instance.getExtensionList(hudson.PluginWrapper$PluginWrapperAdministrativeMonitor.class)[0].disable(true)
instance.getExtensionList(hudson.diagnosis.NullIdDescriptorMonitor.class)[0].disable(true)
instance.getExtensionList(hudson.diagnosis.ReverseProxySetupMonitor.class)[0].disable(true)
instance.getExtensionList(hudson.diagnosis.TooManyJobsButNoView.class)[0].disable(true)
instance.getExtensionList(hudson.model.UpdateCenter$CoreUpdateMonitor.class)[0].disable(true)
instance.getExtensionList(hudson.node_monitors.MonitorMarkedNodeOffline.class)[0].disable(true)
instance.getExtensionList(hudson.plugins.sshslaves.verifiers.MissingVerificationStrategyAdministrativeMonitor.class)[0].disable(true)
instance.getExtensionList(hudson.security.DangerousMatrixPermissionsAdministrativeMonitor.class)[0].disable(true)
instance.getExtensionList(hudson.triggers.SCMTrigger$AdministrativeMonitorImpl.class)[0].disable(true)
instance.getExtensionList(jenkins.branch.PropertyMigration$MonitorImpl.class)[0].disable(true)
instance.getExtensionList(jenkins.diagnosis.HsErrPidList.class)[0].disable(true)
instance.getExtensionList(jenkins.diagnostics.CompletedInitializationMonitor.class)[0].disable(true)
instance.getExtensionList(jenkins.diagnostics.SecurityIsOffMonitor.class)[0].disable(true)
instance.getExtensionList(jenkins.diagnostics.URICheckEncodingMonitor.class)[0].disable(true)
instance.getExtensionList(jenkins.model.DownloadSettings$Warning.class)[0].disable(true)
instance.getExtensionList(jenkins.model.Jenkins$EnforceSlaveAgentPortAdministrativeMonitor.class)[0].disable(true)
instance.getExtensionList(jenkins.security.QueueItemAuthenticatorMonitor.class)[0].disable(true)
instance.getExtensionList(jenkins.security.RekeySecretAdminMonitor.class)[0].disable(true)
instance.getExtensionList(jenkins.security.UpdateSiteWarningsMonitor.class)[0].disable(true)
instance.getExtensionList(jenkins.security.apitoken.ApiTokenPropertyDisabledDefaultAdministrativeMonitor.class)[0].disable(true)
instance.getExtensionList(jenkins.security.apitoken.ApiTokenPropertyEnabledNewLegacyAdministrativeMonitor.class)[0].disable(true)
instance.getExtensionList(jenkins.security.csrf.CSRFAdministrativeMonitor.class)[0].disable(true)
instance.getExtensionList(jenkins.slaves.DeprecatedAgentProtocolMonitor.class)[0].disable(true)
instance.getExtensionList(org.jenkinsci.plugins.pipeline.maven.NonProductionGradeDatabaseWarningAdministrativeMonitor.class)[0].disable(true)
instance.getExtensionList(org.jenkinsci.plugins.rolestrategy.permissions.DangerousPermissionAdministrativeMonitor.class)[0].disable(true)
instance.getExtensionList(jenkins.diagnostics.RootUrlNotSetMonitor.class)[0].disable(true)
